/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0b141c',
        surface: '#0b141c',
        'surface-dim': '#0b141c',
        'surface-bright': '#313a43',
        'surface-container-lowest': '#060f16',
        'surface-container-low': '#141c24',
        'surface-container': '#182028',
        'surface-container-high': '#222b33',
        'surface-container-highest': '#2d363e',
        'surface-variant': '#2d363e',
        'on-surface': '#dae3ee',
        'on-surface-variant': '#bcc9c6',
        outline: '#869391',
        'outline-variant': '#3d4947',
        primary: '#66d9cc',
        'primary-container': '#26a69a',
        'on-primary': '#003732',
        'on-primary-container': '#003430',
        'primary-fixed': '#84f5e8',
        'primary-fixed-dim': '#66d9cc',
        secondary: '#a2c9ff',
        'secondary-container': '#0071c7',
        'on-secondary': '#00315c',
        'on-secondary-container': '#f0f4ff',
        tertiary: '#d3bbff',
        'tertiary-container': '#a97cff',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          900: '#0c4a6e',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'telemetry-display': ['JetBrains Mono', 'monospace'],
        'telemetry-unit': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      spacing: {
        margin: '0.75rem',
        gutter: '0.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.375rem',
        'space-md': '0.5rem',
        'space-lg': '0.75rem',
        'space-xl': '1rem',
      },
    },
  },
  plugins: [],
};
