apiVersion: v1
kind: ServiceAccount
metadata:
  name: bda-service-account
  namespace: bda-energy
  labels:
    app.kubernetes.io/part-of: energy-analytics-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bda-workload-role
  namespace: bda-energy
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bda-workload-binding
  namespace: bda-energy
subjects:
  - kind: ServiceAccount
    name: bda-service-account
    namespace: bda-energy
roleRef:
  kind: Role
  name: bda-workload-role
  apiGroup: rbac.authorization.k8s.io
